@startuml
class User {
    + Username : string <<get>> <<set>>
    + Password : string <<get>> <<set>>
    + Email : string <<get>> <<set>>
    + Domain : string <<get>> <<set>>
    + SecurityLevel : int <<get>> <<set>>
}
User --> "Role" Role
@enduml
