@startuml
!include .\\Aflevering_Del1\Program.puml
!include .\\Aflevering_Frontend\Program.puml
!include .\\Shared\Post.puml
!include .\\Shared\Role.puml
!include .\\Shared\SubComment.puml
!include .\\Shared\User.puml
!include .\\Aflevering_Del1\Controllers\AuthController.puml
!include .\\Aflevering_Del1\Controllers\PostsController.puml
!include .\\Aflevering_Del1\Dao\IPostDao.puml
!include .\\Aflevering_Del1\Dao\IUserDao.puml
!include .\\Aflevering_Del1\Dao\PostDao.puml
!include .\\Aflevering_Del1\Dao\UserDao.puml
!include .\\Aflevering_Del1\Exceptions\PostListNotFound.puml
!include .\\Aflevering_Del1\Exceptions\PostNotFoundException.puml
!include .\\Aflevering_Del1\Exceptions\PostNotSaved.puml
!include .\\Aflevering_Del1\Exceptions\UserAlreadyExistsException.puml
!include .\\Aflevering_Del1\Exceptions\UserNotFoundException.puml
!include .\\Aflevering_Del1\Services\AuthService.puml
!include .\\Aflevering_Del1\Services\IAuthService.puml
!include .\\Aflevering_Del1\Services\IPostService.puml
!include .\\Aflevering_Del1\Services\PostService.puml
!include .\\Aflevering_Frontend\Auth\CustomAuthProvider.puml
!include .\\Aflevering_Frontend\Services\IPostService.puml
!include .\\Aflevering_Frontend\Services\PostService.puml
!include .\\Shared\Auth\AuthorizationPolicies.puml
!include .\\Shared\Dto\PostDto.puml
!include .\\Shared\Dto\UserDto.puml
!include .\\Shared\Dto\UserLoginDto.puml
!include .\\Aflevering_Frontend\Services\Auth\IAuthService.puml
!include .\\Aflevering_Frontend\Services\Auth\JwtAuthService.puml
!include .\\Aflevering_Del1\obj\Debug\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\Aflevering_Del1\obj\Debug\net7.0\Aflevering_Del1.AssemblyInfo.puml
!include .\\Aflevering_Del1\obj\Debug\net7.0\Aflevering_Del1.GlobalUsings.g.puml
!include .\\Aflevering_Del1\obj\Debug\net7.0\Aflevering_Del1.MvcApplicationPartsAssemblyInfo.puml
!include .\\Aflevering_Frontend\obj\Debug\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\Aflevering_Frontend\obj\Debug\net7.0\Aflevering_Frontend.AssemblyInfo.puml
!include .\\Aflevering_Frontend\obj\Debug\net7.0\Aflevering_Frontend.GlobalUsings.g.puml
!include .\\Shared\obj\Debug\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\Shared\obj\Debug\net7.0\Shared.AssemblyInfo.puml
!include .\\Shared\obj\Debug\net7.0\Shared.GlobalUsings.g.puml
@enduml
